import PorydawApp
import PorydawCore

func runVelocityGestureParityChecks(_ report: CheckReport) {
    let lifecycleID = "keyboard/VelocityModelTest::gestureLifecycle"
    let atomicityID = "keyboard/VelocityModelTest::gestureAtomicity"
    let completionID = "keyboard/VelocityModelTest::gestureCompletionAndDeltaFromOriginals"
    let clampedID = "keyboard/VelocityModelTest::gestureClampedDeltaAndCancellation"
    let first = NoteVelocity(noteID: NoteID(1), velocity: 40)
    let second = NoteVelocity(noteID: NoteID(2), velocity: 120)
    var lifecycle = VelocityGestureModel()
    report.expect(!lifecycle.active, cppID: lifecycleID, message: "A001 fresh gesture reports inactive")
    let a002 = lifecycle.update([first])
    report.expect(!a002, cppID: lifecycleID, message: "A002 update while inactive fails")
    report.expect(lifecycle.previewVelocity(first.noteID) == nil, cppID: lifecycleID, message: "A003 preview while inactive is empty")
    let a004 = lifecycle.takeCompletion()
    report.expect(a004 == nil, cppID: lifecycleID, message: "A004 completion while inactive is empty")
    let a005 = lifecycle.cancel()
    report.expect(!a005, cppID: lifecycleID, message: "A005 cancel while inactive fails")
    let a006 = lifecycle.begin(42, [])
    report.expect(!a006, cppID: lifecycleID, message: "A006 begin rejects an empty target list")
    let a007 = lifecycle.begin(42, [NoteVelocity(noteID: NoteID(), velocity: 40)])
    report.expect(!a007, cppID: lifecycleID, message: "A007 begin rejects an unassigned note")
    let a008 = lifecycle.begin(42, [NoteVelocity(noteID: NoteID(3), velocity: 0)])
    report.expect(!a008, cppID: lifecycleID, message: "A008 begin rejects velocity below the MIDI floor")
    let a009 = lifecycle.begin(42, [NoteVelocity(noteID: NoteID(3), velocity: 128)])
    report.expect(!a009, cppID: lifecycleID, message: "A009 begin rejects velocity above the MIDI ceiling")
    let a010 = lifecycle.begin(42, [first, first])
    report.expect(!a010, cppID: lifecycleID, message: "A010 begin rejects a duplicated target")
    let a011 = lifecycle.begin(42, [first, second, second])
    report.expect(!a011, cppID: lifecycleID, message: "A011 begin rejects a duplicated target in a longer list")
    report.expect(!lifecycle.active, cppID: lifecycleID, message: "A012 failed begins leave the gesture inactive")
    let a013 = lifecycle.begin(42, [second, first])
    report.expect(a013, cppID: lifecycleID, message: "A013 begin accepts an unsorted target pair")
    report.expect(lifecycle.active, cppID: lifecycleID, message: "A014 accepted begin reports active")
    report.expectEqual(Optional(UInt8(40)), lifecycle.previewVelocity(first.noteID), cppID: lifecycleID, what: "A015 first preview holds its begin value")
    report.expectEqual(Optional(UInt8(120)), lifecycle.previewVelocity(second.noteID), cppID: lifecycleID, what: "A016 second preview holds its begin value")
    let a017 = lifecycle.begin(43, [second])
    report.expect(!a017, cppID: lifecycleID, message: "A017 begin while active fails")
    report.expectEqual(Optional(UInt8(40)), lifecycle.previewVelocity(first.noteID), cppID: lifecycleID, what: "A018 failed re-begin keeps the first preview")
    var atomicity = VelocityGestureModel()
    let a019 = atomicity.begin(42, [first, second])
    report.expect(a019, cppID: atomicityID, message: "A019 begin accepts the atomicity pair")
    let a020 = atomicity.update([NoteVelocity(noteID: first.noteID, velocity: 100), NoteVelocity(noteID: NoteID(3), velocity: 64)])
    report.expect(!a020, cppID: atomicityID, message: "A020 update rejects an unknown target")
    report.expectEqual(Optional(UInt8(40)), atomicity.previewVelocity(first.noteID), cppID: atomicityID, what: "A021 rejected update keeps the first preview")
    report.expectEqual(Optional(UInt8(120)), atomicity.previewVelocity(second.noteID), cppID: atomicityID, what: "A022 rejected update keeps the second preview")
    let a023 = atomicity.update([])
    report.expect(!a023, cppID: atomicityID, message: "A023 update rejects an empty list")
    let a024 = atomicity.update([NoteVelocity(noteID: first.noteID, velocity: 100), NoteVelocity(noteID: first.noteID, velocity: 110)])
    report.expect(!a024, cppID: atomicityID, message: "A024 update rejects a duplicated target")
    report.expectEqual(Optional(UInt8(40)), atomicity.previewVelocity(first.noteID), cppID: atomicityID, what: "A025 duplicate update keeps the first preview")
    report.expectEqual(Optional(UInt8(120)), atomicity.previewVelocity(second.noteID), cppID: atomicityID, what: "A026 duplicate update keeps the second preview")
    var finishing = VelocityGestureModel()
    let a027 = finishing.begin(42, [second, first])
    report.expect(a027, cppID: completionID, message: "A027 begin accepts the completion pair")
    let a028 = finishing.update([NoteVelocity(noteID: first.noteID, velocity: 100)])
    report.expect(a028, cppID: completionID, message: "A028 absolute update applies")
    report.expectEqual(Optional(UInt8(100)), finishing.previewVelocity(first.noteID), cppID: completionID, what: "A029 first preview takes the absolute value")
    report.expectEqual(Optional(UInt8(120)), finishing.previewVelocity(second.noteID), cppID: completionID, what: "A030 second preview stays at its begin value")
    let a031 = finishing.updateByDelta(-10)
    report.expect(a031, cppID: completionID, message: "A031 delta from originals applies")
    report.expectEqual(Optional(UInt8(30)), finishing.previewVelocity(first.noteID), cppID: completionID, what: "A032 first preview measures the delta from its origin")
    report.expectEqual(Optional(UInt8(110)), finishing.previewVelocity(second.noteID), cppID: completionID, what: "A033 second preview measures the delta from its origin")
    let completion = finishing.takeCompletion()
    report.expect(completion != nil, cppID: completionID, message: "A034 completion exists after edits")
    report.expectEqual(UInt64(42), completion?.expectedRevision ?? 0, cppID: completionID, what: "A035 completion carries the begin revision")
    report.expectEqual(2, completion?.targets.count ?? -1, cppID: completionID, what: "A036 completion carries both targets")
    report.expectEqual(first.noteID, completion?.targets.first?.noteID ?? NoteID(), cppID: completionID, what: "A037 completion orders the first target by note")
    report.expectEqual(30, completion?.targets.first?.velocity ?? -1, cppID: completionID, what: "A038 completion carries the first delta value")
    report.expectEqual(second.noteID, completion?.targets.last?.noteID ?? NoteID(), cppID: completionID, what: "A039 completion orders the second target by note")
    report.expectEqual(110, completion?.targets.last?.velocity ?? -1, cppID: completionID, what: "A040 completion carries the second delta value")
    report.expect(!finishing.active, cppID: completionID, message: "A041 taken completion resets to inactive")
    report.expect(finishing.previewVelocity(first.noteID) == nil, cppID: completionID, message: "A042 preview empties after completion")
    let a043 = finishing.takeCompletion()
    report.expect(a043 == nil, cppID: completionID, message: "A043 second completion is empty")
    var clamped = VelocityGestureModel()
    let a044 = clamped.begin(42, [first, second])
    report.expect(a044, cppID: clampedID, message: "A044 begin accepts the clamped pair")
    let a045 = clamped.update([NoteVelocity(noteID: first.noteID, velocity: 0)])
    report.expect(a045, cppID: clampedID, message: "A045 below-floor update clamps and applies")
    report.expectEqual(Optional(UInt8(1)), clamped.previewVelocity(first.noteID), cppID: clampedID, what: "A046 below-floor preview clamps to the floor")
    let a047 = clamped.update([NoteVelocity(noteID: first.noteID, velocity: 128)])
    report.expect(a047, cppID: clampedID, message: "A047 above-ceiling update clamps and applies")
    report.expectEqual(Optional(UInt8(127)), clamped.previewVelocity(first.noteID), cppID: clampedID, what: "A048 above-ceiling preview clamps to the ceiling")
    let a049 = clamped.updateByDelta(-50)
    report.expect(a049, cppID: clampedID, message: "A049 clamped delta from originals applies")
    report.expectEqual(Optional(UInt8(1)), clamped.previewVelocity(first.noteID), cppID: clampedID, what: "A050 clamped delta floors the first preview")
    report.expectEqual(Optional(UInt8(70)), clamped.previewVelocity(second.noteID), cppID: clampedID, what: "A051 clamped delta moves the second preview from its origin")
    let a052 = clamped.cancel()
    report.expect(a052, cppID: clampedID, message: "A052 cancel while active succeeds")
    report.expect(!clamped.active, cppID: clampedID, message: "A053 cancelled gesture reports inactive")
    report.expect(clamped.previewVelocity(first.noteID) == nil, cppID: clampedID, message: "A054 preview empties after cancel")
    let a055 = clamped.takeCompletion()
    report.expect(a055 == nil, cppID: clampedID, message: "A055 completion empties after cancel")
    let a056 = clamped.cancel()
    report.expect(!a056, cppID: clampedID, message: "A056 second cancel fails")
}
