// Generated by tools/gen_ui_icons.py from resources/icons/manifest.json; do not edit.
pragma Singleton
import QtQuick

QtObject {
    readonly property string family: "Porydaw Icons"
    readonly property var automation: ({ glyph: "\ue000", fit: 1.0000 })
    readonly property var check: ({ glyph: "\ue016", fit: 1.0000 })
    readonly property var closeTab: ({ glyph: "\ue001", fit: 1.0000 })
    readonly property var comboArrow: ({ glyph: "\ue017", fit: 1.0000 })
    readonly property var disclosureClosed: ({ glyph: "\ue01b", fit: 1.0000 })
    readonly property var disclosureOpen: ({ glyph: "\ue01c", fit: 1.0000 })
    readonly property var drumkit: ({ glyph: "\ue002", fit: 1.0000 })
    readonly property var editSample: ({ glyph: "\ue003", fit: 1.0000 })
    readonly property var flat: ({ glyph: "\ue004", fit: 1.0000 })
    readonly property var followPlayhead: ({ glyph: "\ue005", fit: 1.0000 })
    readonly property var goToStart: ({ glyph: "\ue006", fit: 1.0000 })
    readonly property var keysplit: ({ glyph: "\ue007", fit: 0.8889 })
    readonly property var loop: ({ glyph: "\ue008", fit: 1.0000 })
    readonly property var noise: ({ glyph: "\ue009", fit: 0.8000 })
    readonly property var pause: ({ glyph: "\ue00a", fit: 1.0000 })
    readonly property var play: ({ glyph: "\ue00b", fit: 1.0000 })
    readonly property var resonance: ({ glyph: "\ue00c", fit: 1.0000 })
    readonly property var sample: ({ glyph: "\ue00d", fit: 0.8000 })
    readonly property var scrollTabsLeft: ({ glyph: "\ue00e", fit: 1.0000 })
    readonly property var scrollTabsRight: ({ glyph: "\ue00f", fit: 1.0000 })
    readonly property var spinDown: ({ glyph: "\ue018", fit: 1.0000 })
    readonly property var spinUp: ({ glyph: "\ue019", fit: 1.0000 })
    readonly property var square1: ({ glyph: "\ue010", fit: 0.8000 })
    readonly property var square2: ({ glyph: "\ue011", fit: 0.8000 })
    readonly property var stop: ({ glyph: "\ue012", fit: 1.0000 })
    readonly property var submenuArrow: ({ glyph: "\ue01a", fit: 1.0000 })
    readonly property var velocity: ({ glyph: "\ue013", fit: 1.0000 })
    readonly property var velocityLabels: ({ glyph: "\ue014", fit: 1.0000 })
    readonly property var wave: ({ glyph: "\ue015", fit: 0.8000 })
}
