	.align 2
DirectSoundWaveData_fixture_loop::
	.incbin "sound/direct_sound_samples/fixture_loop.bin"

	.align 2
DirectSoundWaveData_fixture_pluck::
	.incbin "sound/direct_sound_samples/fixture_pluck.bin"

	.align 2
DirectSoundWaveData_fixture_bass::
	.incbin "sound/direct_sound_samples/fixture_bass.bin"

	.align 2
DirectSoundWaveData_fixture_drum::
	.incbin "sound/direct_sound_samples/fixture_drum.bin"
