	.equiv MUSIC_PLAYER_BGM, 0
	.equiv MUSIC_PLAYER_SE1, 1
	.equiv MUSIC_PLAYER_SE2, 2
	.equiv MUSIC_PLAYER_SE3, 3
	.equiv MUSIC_PLAYER_SE_1TRK, 4

	.align 2
gSongTable::
	song mus_dummy, MUSIC_PLAYER_BGM, 0
	song mus_littleroot_test, MUSIC_PLAYER_BGM, 0
	song mus_route101, MUSIC_PLAYER_BGM, 0
	song mus_route102, MUSIC_PLAYER_BGM, 0
	song mus_gsc_route38, MUSIC_PLAYER_BGM, 0
	song mus_caught, MUSIC_PLAYER_BGM, 0
	song mus_petalburg, MUSIC_PLAYER_BGM, 0
	song mus_oldale, MUSIC_PLAYER_BGM, 0
	song mus_gym, MUSIC_PLAYER_BGM, 0
	song mus_surf, MUSIC_PLAYER_BGM, 0
	song mus_victory_wild, MUSIC_PLAYER_BGM, 0
	song se_use_item, MUSIC_PLAYER_SE1, 1
	song se_pc_login, MUSIC_PLAYER_SE1, 1
	song se_fanfare_1trk, MUSIC_PLAYER_SE_1TRK, 4
