import PorydawProjectNative

private struct BlankSlotInsertion {
    let index: Int
    let headerIndex: Int?
    let startingSlot: Int
    let additions: [SourceLine]
}

extension VoicegroupSource {
    /// Changes an editable voice or inserts a voice in an undefined slot.
    /// - Parameters:
    ///   - slot: Zero-based bank slot.
    ///   - voice: Voice arguments to render.
    /// - Returns: False for invalid, read-only, broken, or unfillable slots.
    public func setVoice(slot: Int, voice: VgVoice) -> Bool {
        guard (0..<128).contains(slot) else { return false }
        switch kindAt(slot: slot) {
        case .editable:
            let index = slotToLine[slot]
            lines[index].voice = voice
            renderVoiceLine(at: index)
        case .none:
            guard let insertion = blankSlotInsertion(slot: slot, voice: voice) else { return false }
            apply(insertion)
        case .other, .header, .readOnlyVoice, .broken:
            return false
        }
        dirty = !matchesPristineSource()
        return true
    }

    /// Inserts a voice only if its slot remains undefined, recording a narrow undo delta.
    /// - Parameters:
    ///   - slot: Zero-based bank slot.
    ///   - voice: Voice arguments to insert.
    /// - Returns: Generated source bytes and header change, or nil for a conflict.
    public func materializeBlankSlot(slot: Int, voice: VgVoice) -> BlankSlotMaterialization? {
        guard (0..<128).contains(slot), kindAt(slot: slot) == .none,
              let insertion = blankSlotInsertion(slot: slot, voice: voice) else { return nil }
        let headerBefore = insertion.headerIndex.map { lines[$0].raw } ?? []
        apply(insertion)
        dirty = !matchesPristineSource()
        return BlankSlotMaterialization(
            firstAddedSlot: insertion.additions[0].slot,
            addedLines: insertion.additions.map(\.raw),
            rewroteHeader: insertion.headerIndex != nil,
            headerBefore: headerBefore,
            headerAfter: insertion.headerIndex.map { lines[$0].raw } ?? []
        )
    }

    /// Removes only the unchanged generated lines and restores an unchanged rewritten header.
    /// - Parameter materialization: The original insertion's narrow undo delta.
    /// - Returns: False if any generated byte or header no longer matches.
    public func revertBlankSlotMaterialization(_ materialization: BlankSlotMaterialization) -> Bool {
        let first = materialization.firstAddedSlot
        let count = materialization.addedLines.count
        guard first >= 0, count > 0, first < 128, count <= 128 - first else { return false }
        let header = materialization.rewroteHeader ? headerIndex() : nil
        if materialization.rewroteHeader {
            guard let header, lines[header].raw == materialization.headerAfter else { return false }
        }
        for offset in 0..<count {
            let index = slotToLine[first + offset]
            guard index >= 0, lines[index].kind == .editable,
                  lines[index].raw == materialization.addedLines[offset] else { return false }
        }
        if let header { lines[header].raw = materialization.headerBefore }
        for offset in (0..<count).reversed() {
            lines.remove(at: slotToLine[first + offset])
        }
        sectionEnd -= count
        rebuildSlotToLine()
        dirty = !matchesPristineSource()
        return true
    }

    /// Joins the whole source, including the original trailing-LF convention.
    /// - Returns: Current complete file bytes.
    public func sourceBytes() -> [UInt8] {
        guard !lines.isEmpty else { return [] }
        let capacity = lines.reduce(endsWithNewline ? 1 : 0) { $0 + $1.raw.count + 1 } - 1
        var bytes: [UInt8] = []
        bytes.reserveCapacity(capacity)
        for (index, line) in lines.enumerated() {
            if index != 0 { bytes.append(10) }
            bytes.append(contentsOf: line.raw)
        }
        if endsWithNewline { bytes.append(10) }
        return bytes
    }

    /// Re-parses a captured whole-file buffer without changing the pristine baseline.
    /// - Parameter bytes: Previously captured file bytes.
    /// - Returns: Whether the selected voicegroup section could be parsed.
    public func restoreSourceBytes(_ bytes: [UInt8]) -> Bool {
        var error: String?
        let parsed = parse(bytes, error: &error)
        dirty = !matchesPristineSource()
        return parsed
    }

    /// Adopts a detached save only if the saved snapshot still matches the current source.
    /// - Parameter savedBytes: The bytes written by the detached worker.
    /// - Returns: False if another edit superseded the saved snapshot.
    public func didSave(savedBytes: [UInt8]) -> Bool {
        guard sourceBytes() == savedBytes else { return false }
        pristineSource = savedBytes
        dirty = false
        return true
    }

    /// Packs scalar edits into an already-loaded voice of the same native type.
    /// The caller must reload instead if `vgVoiceStructuralChange` is true.
    /// - Parameters:
    ///   - slot: The edited voice slot.
    ///   - toneData: Mutable native tone from the current bank.
    /// - Returns: False for an uneditable slot or native voice-type mismatch.
    public func applyScalarsToToneData(slot: Int, toneData: UnsafeMutablePointer<ToneData>?) -> Bool {
        guard let voice = voiceAt(slot: slot), let toneData,
              toneData.pointee.type == vgMacroVoiceType(voice.macro) else { return false }
        switch voice.macro {
        case .keysplit, .keysplitAll:
            return true
        case .directSound, .directSoundNoResample, .directSoundAlt,
             .square1, .square1Alt, .square2, .square2Alt,
             .progWave, .progWaveAlt, .noise, .noiseAlt:
            break
        }
        toneData.pointee.key = UInt8(truncatingIfNeeded: voice.key)
        if !vgMacroIsCgb(voice.macro) {
            toneData.pointee.panSweep = voice.pan == 0 ? 0 : 0x80 | UInt8(truncatingIfNeeded: voice.pan)
            toneData.pointee.attack = UInt8(truncatingIfNeeded: voice.attack)
            toneData.pointee.decay = UInt8(truncatingIfNeeded: voice.decay)
            toneData.pointee.sustain = UInt8(truncatingIfNeeded: voice.sustain)
            toneData.pointee.release = UInt8(truncatingIfNeeded: voice.release)
            return true
        }
        toneData.pointee.attack = UInt8(truncatingIfNeeded: voice.attack & 0x07)
        toneData.pointee.decay = UInt8(truncatingIfNeeded: voice.decay & 0x07)
        toneData.pointee.sustain = UInt8(truncatingIfNeeded: voice.sustain & 0x0F)
        toneData.pointee.release = UInt8(truncatingIfNeeded: voice.release & 0x07)
        switch voice.macro {
        case .square1, .square1Alt:
            toneData.pointee.panSweep = UInt8(truncatingIfNeeded: voice.sweep)
            toneData.pointee.wavePointer = UnsafeMutablePointer<UInt32>(bitPattern: voice.duty & 0x03)
        case .square2, .square2Alt:
            toneData.pointee.panSweep = 0
            toneData.pointee.wavePointer = UnsafeMutablePointer<UInt32>(bitPattern: voice.duty & 0x03)
        case .noise, .noiseAlt:
            toneData.pointee.wavePointer = UnsafeMutablePointer<UInt32>(bitPattern: voice.period & 0x01)
        case .progWave, .progWaveAlt:
            break // This pointer owns loaded wave data.
        case .directSound, .directSoundNoResample, .directSoundAlt, .keysplit, .keysplitAll:
            break
        }
        return true
    }
}

private extension VoicegroupSource {
    func matchesPristineSource() -> Bool {
        var offset = 0
        for (index, line) in lines.enumerated() {
            if index != 0 {
                guard offset < pristineSource.count, pristineSource[offset] == 10 else { return false }
                offset += 1
            }
            guard line.raw.count <= pristineSource.count - offset else { return false }
            for byte in line.raw {
                guard pristineSource[offset] == byte else { return false }
                offset += 1
            }
        }
        if endsWithNewline && !lines.isEmpty {
            guard offset < pristineSource.count, pristineSource[offset] == 10 else { return false }
            offset += 1
        }
        return offset == pristineSource.count
    }

    func rebuildSlotToLine() {
        slotToLine = [Int](repeating: -1, count: 128)
        for (index, line) in lines.enumerated() where (0..<128).contains(line.slot) {
            slotToLine[line.slot] = index
        }
    }

    func headerIndex() -> Int? {
        let begin = isMonolithic ? sectionBegin : 0
        let end = isMonolithic ? sectionEnd : lines.count
        guard begin >= 0, end <= lines.count else { return nil }
        return (begin..<end).first { lines[$0].kind == .header }
    }

    func generatedVoiceLine(slot: Int, voice: VgVoice, ending: [UInt8]) -> SourceLine {
        var line = SourceLine(raw: [])
        line.kind = .editable
        line.slot = slot
        line.voice = voice
        line.indent = [9]
        line.tail = ending
        render(&line)
        return line
    }

    func silentPaddingVoice() -> VgVoice {
        VgVoice(macro: .square1, sustain: 15, release: 0)
    }

    func blankSlotInsertion(slot: Int, voice: VgVoice) -> BlankSlotInsertion? {
        let first = slotToLine.firstIndex(where: { $0 >= 0 })
        let last = slotToLine.lastIndex(where: { $0 >= 0 })
        let header = headerIndex()
        var additions: [SourceLine] = []
        let padding = silentPaddingVoice()
        let ending: [UInt8] = lines.contains(where: { $0.raw.last == 13 }) ? [13] : []
        let insertionIndex: Int
        let rewrite: Int?
        if first == nil {
            insertionIndex = header.map { $0 + 1 } ??
                min(isMonolithic ? sectionBegin + 1 : 1, lines.count)
            rewrite = header
            if header == nil {
                for current in 0..<slot {
                    additions.append(generatedVoiceLine(slot: current, voice: padding, ending: ending))
                }
            }
        } else if let first, slot < first {
            guard let header else { return nil }
            insertionIndex = slotToLine[first]
            rewrite = header
        } else if let last, slot > last {
            insertionIndex = slotToLine[last] + 1
            rewrite = nil
            for current in (last + 1)..<slot {
                additions.append(generatedVoiceLine(slot: current, voice: padding, ending: ending))
            }
        } else {
            return nil // An existing voice group occupies the entire span between its ends.
        }
        additions.append(generatedVoiceLine(slot: slot, voice: voice, ending: ending))
        if let first, slot < first {
            for current in (slot + 1)..<first {
                additions.append(generatedVoiceLine(slot: current, voice: padding, ending: ending))
            }
        }
        return BlankSlotInsertion(index: insertionIndex, headerIndex: rewrite,
                                  startingSlot: slot, additions: additions)
    }

    func apply(_ insertion: BlankSlotInsertion) {
        if let header = insertion.headerIndex {
            rewriteHeaderStartingSlot(at: header, to: insertion.startingSlot)
        }
        lines.insert(contentsOf: insertion.additions, at: insertion.index)
        sectionEnd += insertion.additions.count
        rebuildSlotToLine()
    }

    func rewriteHeaderStartingSlot(at index: Int, to slot: Int) {
        var line = lines[index]
        let bounds = contentBounds(line.raw)
        let text = line.raw[bounds]
        let declaration = text.prefix { $0 != 44 }
        var replacement = Array(declaration)
        if slot > 0 {
            replacement.append(contentsOf: Array(", \(slot)".utf8))
        }
        line.raw.replaceSubrange(bounds, with: replacement)
        lines[index] = line
    }

    func renderVoiceLine(at index: Int) {
        var line = lines[index]
        render(&line)
        lines[index] = line
    }

    func render(_ line: inout SourceLine) {
        let voice = line.voice
        var values: [[UInt8]] = []
        if voice.macro == .keysplitAll {
            values.append(Array(voice.symbol.utf8))
        } else if voice.macro == .keysplit {
            values = [Array(voice.symbol.utf8), Array(voice.keysplitTable.utf8)]
        } else {
            values = [Array(String(voice.key).utf8), Array(String(voice.pan).utf8)]
            if vgMacroHasSymbol(voice.macro) {
                values.append(Array(voice.symbol.utf8))
            } else if voice.macro == .square1 || voice.macro == .square1Alt {
                values.append(Array(String(voice.sweep).utf8))
                values.append(Array(String(voice.duty).utf8))
            } else if voice.macro == .square2 || voice.macro == .square2Alt {
                values.append(Array(String(voice.duty).utf8))
            } else {
                values.append(Array(String(voice.period).utf8))
            }
            values.append(contentsOf: [voice.attack, voice.decay, voice.sustain, voice.release]
                .map { Array(String($0).utf8) })
        }
        let macroWord = Array(vgMacroName(voice.macro).utf8)
        if trimWhitespace(line.macroText) == macroWord && line.argPieces.count == values.count {
            for index in values.indices {
                let piece = line.argPieces[index]
                let leading = piece.prefix(while: isWhitespace)
                let trailing = piece.reversed().prefix(while: isWhitespace).reversed()
                line.argPieces[index] = Array(leading) + values[index] + Array(trailing)
            }
        } else {
            line.macroText = macroWord + [32]
            line.argPieces = values.enumerated().map { index, value in index == 0 ? value : [32] + value }
        }
        var raw = line.indent + line.macroText
        for (index, piece) in line.argPieces.enumerated() {
            if index != 0 { raw.append(44) }
            raw.append(contentsOf: piece)
        }
        raw.append(contentsOf: line.tail)
        line.raw = raw
    }

    func contentBounds(_ raw: [UInt8]) -> Range<Int> {
        var end = raw.firstIndex(of: 64) ?? raw.count
        if raw.count >= 2 {
            for index in 0..<(raw.count - 1) where raw[index] == 47 && raw[index + 1] == 47 {
                end = min(end, index)
                break
            }
        }
        while end > 0 && isWhitespace(raw[end - 1]) { end -= 1 }
        var start = 0
        while start < end && isWhitespace(raw[start]) { start += 1 }
        return start..<end
    }

    func trimWhitespace(_ bytes: [UInt8]) -> [UInt8] {
        let leading = bytes.prefix(while: isWhitespace).count
        let trailing = bytes.reversed().prefix(while: isWhitespace).count
        return Array(bytes[leading..<(max(leading, bytes.count - trailing))])
    }

    func isWhitespace(_ byte: UInt8) -> Bool { byte == 32 || (9...13).contains(byte) }
}
