import Foundation
import PorydawProjectNative

/// Editable voice macros in the frozen C++ ordinal order used by PdVoiceValue.
public enum VgMacro: Int32, CaseIterable, Sendable {
    case directSound = 0
    case directSoundNoResample
    case directSoundAlt
    case square1
    case square1Alt
    case square2
    case square2Alt
    case progWave
    case progWaveAlt
    case noise
    case noiseAlt
    case keysplit
    case keysplitAll
}

/// The raw arguments of one editable voice macro, before ToneData packing.
public struct VgVoice: Equatable, Sendable {
    public var macro: VgMacro
    public var key: Int
    public var pan: Int
    public var symbol: String
    public var keysplitTable: String
    public var sweep: Int
    public var duty: Int
    public var period: Int
    public var attack: Int
    public var decay: Int
    public var sustain: Int
    public var release: Int

    public init(macro: VgMacro = .directSound, key: Int = 60, pan: Int = 0,
                symbol: String = "", keysplitTable: String = "", sweep: Int = 0,
                duty: Int = 2, period: Int = 0, attack: Int = 0, decay: Int = 0,
                sustain: Int = 0, release: Int = 0) {
        self.macro = macro
        self.key = key
        self.pan = pan
        self.symbol = symbol
        self.keysplitTable = keysplitTable
        self.sweep = sweep
        self.duty = duty
        self.period = period
        self.attack = attack
        self.decay = decay
        self.sustain = sustain
        self.release = release
    }
}

/// A parsed voice or a template for a blank slot.
public struct VgVoiceDraft: Equatable, Sendable {
    public var voice: VgVoice
    public var materializesBlank: Bool

    public init(voice: VgVoice, materializesBlank: Bool = false) {
        self.voice = voice
        self.materializesBlank = materializesBlank
    }
}

/// Envelope values on their voice family's raw macro-argument scale.
public struct VgAdsr: Equatable, Sendable {
    public var attack: Int
    public var decay: Int
    public var sustain: Int
    public var release: Int

    public init(attack: Int = 0, decay: Int = 0, sustain: Int = 0, release: Int = 0) {
        self.attack = attack
        self.decay = decay
        self.sustain = sustain
        self.release = release
    }
}

/// Project-typical audible envelopes, indexed by symbol and envelope family.
public struct VgAdsrDefaults: Sendable {
    public var bySymbol: [String: VgAdsr]
    public var byFamily: [Int: VgAdsr]

    public init(bySymbol: [String: VgAdsr] = [:], byFamily: [Int: VgAdsr] = [:]) {
        self.bySymbol = bySymbol
        self.byFamily = byFamily
    }
}

/// A Golden Sun synth waveform; non-pulse waveforms ignore pulse parameters.
public struct VgSynthDesc: Equatable, Sendable {
    public var waveform: Int
    public var baseDuty: Int
    public var dutyStep: Int
    public var modDepth: Int
    public var phase: Int

    public init(waveform: Int = 0, baseDuty: Int = 0x80, dutyStep: Int = 0,
                modDepth: Int = 0, phase: Int = 0) {
        self.waveform = waveform
        self.baseDuty = baseDuty
        self.dutyStep = dutyStep
        self.modDepth = modDepth
        self.phase = phase
    }

    public static func == (lhs: VgSynthDesc, rhs: VgSynthDesc) -> Bool {
        guard lhs.waveform == rhs.waveform else { return false }
        return lhs.waveform != 0 ||
            (lhs.baseDuty == rhs.baseDuty && lhs.dutyStep == rhs.dutyStep &&
             lhs.modDepth == rhs.modDepth && lhs.phase == rhs.phase)
    }
}

/// Source-line categories, retaining the C++ ordinal order for published slots.
public enum VgLineKind: Int32, Sendable {
    case none = 0
    case other
    case header
    case editable
    case readOnlyVoice
    case broken
}

/// Exact source category and editable voice, when present, for one bank slot.
public struct VoicegroupSlotView: Sendable {
    public var kind: VgLineKind
    public var voice: VgVoice?

    public init(kind: VgLineKind = .none, voice: VgVoice? = nil) {
        self.kind = kind
        self.voice = voice
    }
}

/// Immutable publication of bank state; the bank handle owns its native bank.
public struct LoadedBankView: Sendable {
    public let id: VoicegroupId
    public let bank: BankHandle
    public let loadName: String
    public let dirty: Bool
    public let slotViews: [VoicegroupSlotView]

    public init(id: VoicegroupId, bank: BankHandle, loadName: String, dirty: Bool,
                slotViews: [VoicegroupSlotView]) {
        self.id = id
        self.bank = bank
        self.loadName = loadName
        self.dirty = dirty
        self.slotViews = slotViews
    }
}

/// The generated bytes required to undo precisely one blank-slot insertion.
public struct BlankSlotMaterialization: Equatable, Sendable {
    public let firstAddedSlot: Int
    public let addedLines: [[UInt8]]
    public let rewroteHeader: Bool
    public let headerBefore: [UInt8]
    public let headerAfter: [UInt8]

    public init(firstAddedSlot: Int, addedLines: [[UInt8]], rewroteHeader: Bool,
                headerBefore: [UInt8], headerAfter: [UInt8]) {
        self.firstAddedSlot = firstAddedSlot
        self.addedLines = addedLines
        self.rewroteHeader = rewroteHeader
        self.headerBefore = headerBefore
        self.headerAfter = headerAfter
    }
}

/// Set a slot only if its current voice still equals `expected`; nil requires blank.
public struct SetVoicegroupSlot: Sendable {
    public let slot: Int
    public let value: VgVoice
    public let expected: VgVoice?

    public init(slot: Int, value: VgVoice, expected: VgVoice? = nil) {
        self.slot = slot
        self.value = value
        self.expected = expected
    }
}

/// Undo one previously generated blank slot if its exact bytes still match.
public struct RevertBlankSlot: Sendable {
    public let materialization: BlankSlotMaterialization

    public init(materialization: BlankSlotMaterialization) {
        self.materialization = materialization
    }
}

/// The two mutually exclusive voicegroup edit operations.
public enum VoicegroupEditOperation: Sendable {
    case set(SetVoicegroupSlot)
    case revert(RevertBlankSlot)
}

/// One bank edit addressed by source identity.
public struct VoicegroupEditInput: Sendable {
    public let id: VoicegroupId
    public let operation: VoicegroupEditOperation

    public init(id: VoicegroupId, operation: VoicegroupEditOperation) {
        self.id = id
        self.operation = operation
    }
}

/// A published bank after an applied edit, and its optional blank-slot delta and undo token.
public struct VoicegroupEditAppliedResult: Sendable {
    public let view: LoadedBankView
    public let materialization: BlankSlotMaterialization?
    public let materializationToken: UInt64?

    public init(view: LoadedBankView, materialization: BlankSlotMaterialization? = nil,
                materializationToken: UInt64? = nil) {
        self.view = view
        self.materialization = materialization
        self.materializationToken = materializationToken
    }
}

/// An expected mismatch or validation no-op, confirmed not applied.
public struct VoicegroupEditConflictResult: Sendable {
    public let voicegroup: VoicegroupId

    public init(voicegroup: VoicegroupId) {
        self.voicegroup = voicegroup
    }
}

/// The confirmed edit outcome, not a thrown error for expected conflicts.
public enum VoicegroupEditResult: Sendable {
    case applied(VoicegroupEditAppliedResult)
    case conflict(VoicegroupEditConflictResult)
}

/// Save only this voicegroup; synth definitions never cross the store seam.
public struct SaveVoicegroupInput: Sendable {
    public let voicegroup: VoicegroupId

    public init(voicegroup: VoicegroupId) {
        self.voicegroup = voicegroup
    }
}

/// Returns the assembler macro word for an editable voice family.
public func vgMacroName(_ macro: VgMacro) -> String {
    switch macro {
    case .directSound: "voice_directsound"
    case .directSoundNoResample: "voice_directsound_no_resample"
    case .directSoundAlt: "voice_directsound_alt"
    case .square1: "voice_square_1"
    case .square1Alt: "voice_square_1_alt"
    case .square2: "voice_square_2"
    case .square2Alt: "voice_square_2_alt"
    case .progWave: "voice_programmable_wave"
    case .progWaveAlt: "voice_programmable_wave_alt"
    case .noise: "voice_noise"
    case .noiseAlt: "voice_noise_alt"
    case .keysplit: "voice_keysplit"
    case .keysplitAll: "voice_keysplit_all"
    }
}

/// Returns the C++ UI label for an editable voice family.
public func vgMacroDisplayName(_ macro: VgMacro) -> String {
    switch macro {
    case .directSound: "Sample"
    case .directSoundNoResample: "Sample (fixed pitch)"
    case .directSoundAlt: "Sample (reverse)"
    case .square1: "Square 1"
    case .square1Alt: "Square 1 (alt)"
    case .square2: "Square 2"
    case .square2Alt: "Square 2 (alt)"
    case .progWave: "Wave"
    case .progWaveAlt: "Wave (alt)"
    case .noise: "Noise"
    case .noiseAlt: "Noise (alt)"
    case .keysplit: "Keysplit"
    case .keysplitAll: "Drumkit"
    }
}

/// Returns the loader's packed VOICE_* tag, not the VgMacro ordinal.
public func vgMacroVoiceType(_ macro: VgMacro) -> UInt8 {
    switch macro {
    case .directSound: UInt8(VOICE_DIRECTSOUND)
    case .directSoundNoResample: UInt8(VOICE_DIRECTSOUND_NO_RESAMPLE)
    case .directSoundAlt: UInt8(VOICE_DIRECTSOUND_ALT)
    case .square1: UInt8(VOICE_SQUARE_1)
    case .square1Alt: UInt8(VOICE_SQUARE_1_ALT)
    case .square2: UInt8(VOICE_SQUARE_2)
    case .square2Alt: UInt8(VOICE_SQUARE_2_ALT)
    case .progWave: UInt8(VOICE_PROGRAMMABLE_WAVE)
    case .progWaveAlt: UInt8(VOICE_PROGRAMMABLE_WAVE_ALT)
    case .noise: UInt8(VOICE_NOISE)
    case .noiseAlt: UInt8(VOICE_NOISE_ALT)
    case .keysplit: UInt8(VOICE_KEYSPLIT)
    case .keysplitAll: UInt8(VOICE_KEYSPLIT_ALL)
    }
}

/// Returns whether the macro carries a sample, wave, or sub-voicegroup symbol.
public func vgMacroHasSymbol(_ macro: VgMacro) -> Bool {
    switch macro {
    case .directSound, .directSoundNoResample, .directSoundAlt,
         .progWave, .progWaveAlt, .keysplit, .keysplitAll: true
    case .square1, .square1Alt, .square2, .square2Alt, .noise, .noiseAlt: false
    }
}

/// Returns whether the macro uses the narrower CGB envelope scale.
public func vgMacroIsCgb(_ macro: VgMacro) -> Bool {
    switch macro {
    case .directSound, .directSoundNoResample, .directSoundAlt, .keysplit, .keysplitAll: false
    case .square1, .square1Alt, .square2, .square2Alt,
         .progWave, .progWaveAlt, .noise, .noiseAlt: true
    }
}

/// Returns the base macro ordinal for an envelope family, or -1 for no envelope.
public func vgAdsrFamily(_ macro: VgMacro) -> Int {
    switch macro {
    case .directSound, .directSoundNoResample, .directSoundAlt: Int(VgMacro.directSound.rawValue)
    case .square1, .square1Alt: Int(VgMacro.square1.rawValue)
    case .square2, .square2Alt: Int(VgMacro.square2.rawValue)
    case .progWave, .progWaveAlt: Int(VgMacro.progWave.rawValue)
    case .noise, .noiseAlt: Int(VgMacro.noise.rawValue)
    case .keysplit, .keysplitAll: -1
    }
}

/// Returns the displayed Golden Sun waveform name.
public func vgSynthWaveformName(_ waveform: Int) -> String {
    switch waveform {
    case 0: "Pulse"
    case 1: "Sawtooth"
    default: "Triangle"
    }
}

/// Returns the canonical symbol, before any collision suffix is applied.
public func vgSynthSymbolName(_ desc: VgSynthDesc) -> String {
    switch desc.waveform {
    case 0:
        return String(format: "DirectSoundSynth_GoldenSun_%02X%02X%02X%02X",
                      UInt8(truncatingIfNeeded: desc.baseDuty),
                      UInt8(truncatingIfNeeded: desc.dutyStep),
                      UInt8(truncatingIfNeeded: desc.modDepth),
                      UInt8(truncatingIfNeeded: desc.phase))
    case 1: return "DirectSoundSynth_GoldenSun_Saw"
    default: return "DirectSoundSynth_GoldenSun_Triangle"
    }
}

/// Picks the symbol's typical envelope, then its family's, then an audible fallback.
public func vgDefaultAdsr(_ defaults: VgAdsrDefaults, _ macro: VgMacro, _ symbol: String) -> VgAdsr {
    if !symbol.isEmpty, let match = defaults.bySymbol[symbol] { return match }
    if let match = defaults.byFamily[vgAdsrFamily(macro)] { return match }
    return vgMacroIsCgb(macro)
        ? VgAdsr(attack: 0, decay: 0, sustain: 15, release: 3)
        : VgAdsr(attack: 255, decay: 0, sustain: 255, release: 165)
}

/// Returns true when scalar ToneData updates cannot reproduce the edit.
public func vgVoiceStructuralChange(_ before: VgVoice, _ after: VgVoice) -> Bool {
    before.macro != after.macro || before.symbol != after.symbol ||
        before.keysplitTable != after.keysplitTable
}
