#pragma once

#include <QObject>
#include <QString>
#include <QStringList>
#include <QVector>

#include <cstdint>

#include "project/decompproject.h"

// What a staged playable song can exercise, classified once in
// initTestCase so rows are generated only for songs that will really
// run the slot's contract. A required contract with no eligible song
// in the corpus emits a sentinel row that fails instead of silently
// skipping.
struct SongEligibility {
    bool editableTrack = false;
    bool canAddTrack = false;
    bool multiTrack = false;
};

struct PlayableSong {
    SongInfo info;
    SongEligibility eligibility;
};

enum class SongCapability : uint8_t {
    Playable,         // every playable corpus song
    EditableTrack,    // has a track with editable notes
    AddTrack,         // has spare hardware capacity
    DuplicateTrack,   // editable track + spare capacity
    ReorderableTrack, // editable track + at least two engine tracks
};

class EditCheckTest final : public QObject
{
    Q_OBJECT
    Q_DISABLE_COPY_MOVE(EditCheckTest)

  public:
    explicit EditCheckTest(QString projectRoot);

  private slots:
    void initTestCase();

    // Per-song contracts over the staged decomp corpus: each slot has
    // one data row per eligible song (column songLabel), generated by
    // addSongRows from the slot's required capability, and is
    // independently selectable as <slot>:<label>.
    void rawEventMutate_data();
    void rawEventMutate();
    void rawEventReorder_data();
    void rawEventReorder();
    void noteEditingBasic_data();
    void noteEditingBasic();
    void noteEditingBatch_data();
    void noteEditingBatch();
    void noteEditingAbutting_data();
    void noteEditingAbutting();
    void rangeEdit_data();
    void rangeEdit();
    void rangeMove_data();
    void rangeMove();
    void rangeLaneBulk_data();
    void rangeLaneBulk();
    void rangeLaneConverge_data();
    void rangeLaneConverge();
    void noteMoveOverlap_data();
    void noteMoveOverlap();
    void noteMoveMerge_data();
    void noteMoveMerge();
    void noteMoveBatch_data();
    void noteMoveBatch();
    void noteMoveCollision_data();
    void noteMoveCollision();
    void noteMoveRejects_data();
    void noteMoveRejects();
    void timeRangeRemove_data();
    void timeRangeRemove();
    void songWholeSongRemove_data();
    void songWholeSongRemove();
    void voiceLanePoint_data();
    void voiceLanePoint();
    void automationLanePoints_data();
    void automationLanePoints();
    void trackCreateDelete_data();
    void trackCreateDelete();
    void trackDuplicate_data();
    void trackDuplicate();
    void trackMove_data();
    void trackMove();
    void trackMarkerName();
    void trackDeleteRescue_data();
    void trackDeleteRescue();
    void trackRename_data();
    void trackRename();
    void songTimeSignature_data();
    void songTimeSignature();
    void loopCfgUndoRedo_data();
    void loopCfgUndoRedo();

    // Synthetic document contracts: one independently selectable slot
    // per behavior.
    void documentLoadPublication();
    void documentTempoEmpty();
    void documentVelocityAtomic();
    void documentVelocityRejects();
    void documentDuplicateIdentities();
    void documentRemapsAndRaw();
    void documentSavedIdentity();
    void documentDuplicationOwnership();
    void documentGlobalMetadata();
    void documentCrossingIdentities();
    void documentPublicationNetZero();
    void documentMergedOverlapPublication();
    void timeRangeNoOps();
    void timeRangeInsertScopeAndSplit();
    void timeRangeUnterminated();
    void timeRangeDuplicateClippingAndOrder();
    void timeRangeSignatureAndOrphans();
    void timeRangeAutomationSeamsAndDefaults();
    void timeRangeWholeSong();

    // SMF byte-format contracts: foreign/synthetic files and the save
    // pipeline.
    void xcmdSaveSnapshot();
    void formatZeroCoercion();
    void formatZeroGlobals();
    void formatZeroSaveRoundTrip();
    void markerVersusTrackName();
    void duplicateLaneAndTempoLoad();
    void duplicateCanonicalization();
    void duplicateReplacementsAndNoOps();

  private:
    void addSongRows(SongCapability capability) const;
    bool eligible(const PlayableSong &song, SongCapability capability) const;
    SongInfo songForLabel(const QString &label) const;

    QString m_projectRoot;
    QVector<SongInfo> m_songs;
    QVector<PlayableSong> m_playableSongs;
};

class ScaleCheckTest final : public QObject
{
    Q_OBJECT
    Q_DISABLE_COPY_MOVE(ScaleCheckTest)

  public:
    ScaleCheckTest() = default;

  private slots:
    void table_data();
    void table();
    void rootsAndDefaults();
    void membershipAndNeighbors();
    void diatonicDestinations_data();
    void diatonicDestinations();
};

class NoteIdentityCheckTest final : public QObject
{
    Q_OBJECT
    Q_DISABLE_COPY_MOVE(NoteIdentityCheckTest)

  public:
    NoteIdentityCheckTest() = default;

  private slots:
    void parsedMidiLeavesIdsUnassigned();
    void adoptedSmfRemintsForeignIds();
    void identityDoesNotAffectEqualityOrSerialization();
    void timelineTransportsOnlyStampedNoteIds();
    void adoptedIdsDoNotCollideWithEdits();
};

int runEditCheck(const QStringList &checkArguments, const QStringList &qtArguments);
int runScaleCheck(const QStringList &checkArguments, const QStringList &qtArguments);
int runNoteIdentityCheck(const QStringList &checkArguments, const QStringList &qtArguments);
